### ISSUE TITLE
Beacon Location font size issue V0.69

### ISSUE THREAD

**Issue by Knucklebuster620** [ruthsarian/Droid-Toolbox#3]
I think I may have accidentally stumbled upon a bug.  I believe what I did was mistakenly held the S1 button on my TTGO T display on the Beacon/Locations page.  Since then the font size has been larger.  No button presses seem to fix it, I have tried re-uploading to my board with no change. I uploaded an older version of the toolbox. (V0.60) and the font went back to smaller. Uploaded the V0.69 to it again and the problem returned.  I have even selected "erase all flash" during the uploads with no fix.  I did find that if I changed to a different font the size would go back to normal, but as soon as I went back to the original font the fault would return.

Fault occurred while using the basic font.

**Comment by ruthsarian** [comment]
Could you tell me what version of the Arduino IDE you're using and what version of the TFT_eSPI library you have installed? 

When you say the fault would return, would the font immediately become larger as soon as the TTGO powered up or do you mean that you were able to retrigger the bug on the Beacon/Locations page?

Thanks

**Comment by Knucklebuster620** [comment]
Sure. I am running Arduino IDE 1.8.10, I know it's old I've just been sticking with what I know. From what I can tell I'm running TFT_eSPI V2.5.0.

What I'm meaning is the font is only larger on the Beacon/Locations page and no matter what I do (without even attempting to duplicate what I did to make the fault happen) when I open the Beacon/Locations page up again it is already in larger font, unless I run the older toolbox version or change the font type on the first page say to something like Aurebesh_English.

And as another note, It was working fine, been playing with it all morning with my droid until I didn't press the right button to go back.

**Comment by Knucklebuster620** [comment]
Maybe the font was always bigger on the Beacon/Location screen to begin with?  

I went through the code and decided to change line 850 to "lists[LIST_LOCATIONS].render_options.text_size              = MENU_SELECT_TEXT_SIZE - 1;" and now it appears to be showing up in a font that correctly fits the screen.  I could have sworn though that it was this way when I was using the toolbox earlier today.

I have even removed the " - 1" from that line and re-uploaded and the font returned to larger with the font just overrunning the screen, with the "M" and the "e" of Marketplace about 1/3rd off screen on the Beacon/Location page .

I have even used Notepad++'s compare tool to compare my .ino copy with a fresh copy from the Github and the only difference between them is where I added my droids name and address and now the " - 1" i just added.

IDK if this is just a work around for the issue I am having or an issue maybe someone will see but it is working now. 

Thanks for your help, and thanks for creating this toolbox and all the other things you have done!  I enjoy all the information you share and videos you create!

I will leave this as open in case you find a different/better solution to this issue.

**Comment by ruthsarian** [comment]
This is a bug I introduced when I reworked how fonts are displayed when I introduced custom fonts. I merged the font menu settings I was using for the beacon menus with the other menus. I tested with a T-Display-S3, but not a T-Display and missed this. I've updated the code to resolve the issue and published release v0.70. 

When you have a chance, can you try the new code and tell me if it works for you?

Thanks

**Comment by Knucklebuster620** [comment]
Thanks for fixing it!  I have uploaded V0.70 to my T-display and it is working flawlessly.

Thank you so much for the fix!!

**Comment by Elcid8687** [comment]
I also tested and did not see the issueSent from my iPhoneOn Jan 31, 2024, at 3:50 PM, Knucklebuster620 ***@***.***> wrote:﻿
Closed #3 as completed.
