### ISSUE TITLE
Issue when compiling 

### ISSUE THREAD

**Issue by Richs1077** [ruthsarian/Droid-Toolbox#7]
Hi,

when compiling I am getting this error 
I am running the latest IDE version of Arduino, any help would be appreciated :-)
I tried another install on a different laptop following the install step by step but still the same

 1386 |   pAdve rtisementData->setManufacturerData(std::string(reinterpret_cast<char*>(payload), PAYLOAD_SIZE));
      |   ^~~~
C:\Users\Rich\Dropbox\PC (2)\Documents\Arduino\Droid-Toolbox\Droid-Toolbox.ino: In member function 'virtual void MyAdvertisedDeviceCallbacks::onResult(BLEAdvertisedDevice)':
C:\Users\Rich\Dropbox\PC (2)\Documents\Arduino\Droid-Toolbox\Droid-Toolbox.ino:1406:64: error: 'class String' has no member named 'data'
 1406 |     rawdata = (uint8_t*)advertisedDevice.getManufacturerData().data();
      |                                                                ^~~~
C:\Users\Rich\Dropbox\PC (2)\Documents\Arduino\Droid-Toolbox\Droid-Toolbox.ino: In function 'void ble_scan()':
C:\Users\Rich\Dropbox\PC (2)\Documents\Arduino\Droid-Toolbox\Droid-Toolbox.ino:1627:48: error: conversion from 'BLEScanResults*' to non-scalar type 'BLEScanResults' requested
 1627 |   BLEScanResults foundDevices = pBLEScan->start(BLE_SCAN_TIME, false);
      |                                 ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
exit status 1

Compilation error: 'pAdve' was not declared in this scope 

Compilation error: cannot convert 'std::string' (aka'std::__cxx11::basic_string<char>'} to 'string'

**Comment by ruthsarian** [comment]
"pAdve rtisementData" shouldn't have a space in it. delete that space and try recompiling.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Richs1077 ***@***.***>
Sent: Saturday, June 8, 2024 4:16:59 PM
To: ruthsarian/Droid-Toolbox ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ruthsarian/Droid-Toolbox] Issue when compiling (Issue #7)


when compiling I am getting this error
I am running the latest IDE version of Arduino, any help would be appreciated :-)

1386 | pAdve rtisementData->setManufacturerData(std::string(reinterpret_cast<char*>(payload), PAYLOAD_SIZE));
| ^~~~
C:\Users\Rich\Dropbox\PC (2)\Documents\Arduino\Droid-Toolbox\Droid-Toolbox.ino: In member function 'virtual void MyAdvertisedDeviceCallbacks::onResult(BLEAdvertisedDevice)':
C:\Users\Rich\Dropbox\PC (2)\Documents\Arduino\Droid-Toolbox\Droid-Toolbox.ino:1406:64: error: 'class String' has no member named 'data'
1406 | rawdata = (uint8_t*)advertisedDevice.getManufacturerData().data();
| ^~~~
C:\Users\Rich\Dropbox\PC (2)\Documents\Arduino\Droid-Toolbox\Droid-Toolbox.ino: In function 'void ble_scan()':
C:\Users\Rich\Dropbox\PC (2)\Documents\Arduino\Droid-Toolbox\Droid-Toolbox.ino:1627:48: error: conversion from 'BLEScanResults*' to non-scalar type 'BLEScanResults' requested
1627 | BLEScanResults foundDevices = pBLEScan->start(BLE_SCAN_TIME, false);
| ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
exit status 1

Compilation error: 'pAdve' was not declared in this scope

**Comment by Elcid8687** [comment]
I am getting the same error Sent from my iPhoneOn Jun 8, 2024, at 3:29 PM, The Forgettable Mister Ruthsarian ***@***.***> wrote:﻿
"pAdve rtisementData" shouldn't have a space in it. delete that space and try recompiling.



Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

From: Richs1077 ***@***.***>

Sent: Saturday, June 8, 2024 4:16:59 PM

To: ruthsarian/Droid-Toolbox ***@***.***>

Cc: Subscribed ***@***.***>

Subject: [ruthsarian/Droid-Toolbox] Issue when compiling (Issue #7)





when compiling I am getting this error

I am running the latest IDE version of Arduino, any help would be appreciated :-)



1386 | pAdve rtisementData->setManufacturerData(std::string(reinterpret_cast<char*>(payload), PAYLOAD_SIZE));

| ^~~~

C:\Users\Rich\Dropbox\PC (2)\Documents\Arduino\Droid-Toolbox\Droid-Toolbox.ino: In member function 'virtual void MyAdvertisedDeviceCallbacks::onResult(BLEAdvertisedDevice)':

C:\Users\Rich\Dropbox\PC (2)\Documents\Arduino\Droid-Toolbox\Droid-Toolbox.ino:1406:64: error: 'class String' has no member named 'data'

1406 | rawdata = (uint8_t*)advertisedDevice.getManufacturerData().data();

| ^~~~

C:\Users\Rich\Dropbox\PC (2)\Documents\Arduino\Droid-Toolbox\Droid-Toolbox.ino: In function 'void ble_scan()':

C:\Users\Rich\Dropbox\PC (2)\Documents\Arduino\Droid-Toolbox\Droid-Toolbox.ino:1627:48: error: conversion from 'BLEScanResults*' to non-scalar type 'BLEScanResults' requested

1627 | BLEScanResults foundDevices = pBLEScan->start(BLE_SCAN_TIME, false);

| ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~

exit status 1



Compilation error: 'pAdve' was not declared in this scope

**Comment by Richs1077** [comment]
thanks so much for the replies, I have removed the space but still no joy :-(


C:\Users\Rich\Dropbox\PC (2)\Documents\Arduino\Droid-Toolbox\Droid-Toolbox.ino: In function 'void set_payload_from_beacon()':
C:\Users\Rich\Dropbox\PC (2)\Documents\Arduino\Droid-Toolbox\Droid-Toolbox.ino:1386:48: error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'
 1386 |   pAdvertisementData->setManufacturerData(std::string(reinterpret_cast<char*>(payload), PAYLOAD_SIZE));
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                |
      |                                                std::string {aka std::__cxx11::basic_string<char>}
In file included from C:\Users\Rich\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.1\libraries\BLE\src/BLEServer.h:22,
                 from C:\Users\Rich\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.1\libraries\BLE\src/BLEDevice.h:21,
                 from C:\Users\Rich\Dropbox\PC (2)\Documents\Arduino\Droid-Toolbox\Droid-Toolbox.ino:184:
C:\Users\Rich\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.1\libraries\BLE\src/BLEAdvertising.h:31:35: note:   initializing argument 1 of 'void BLEAdvertisementData::setManufacturerData(String)'
   31 |   void setManufacturerData(String data);
      |                            ~~~~~~~^~~~
C:\Users\Rich\Dropbox\PC (2)\Documents\Arduino\Droid-Toolbox\Droid-Toolbox.ino: In member function 'virtual void MyAdvertisedDeviceCallbacks::onResult(BLEAdvertisedDevice)':
C:\Users\Rich\Dropbox\PC (2)\Documents\Arduino\Droid-Toolbox\Droid-Toolbox.ino:1406:64: error: 'class String' has no member named 'data'
 1406 |     rawdata = (uint8_t*)advertisedDevice.getManufacturerData().data();
      |                                                                ^~~~
C:\Users\Rich\Dropbox\PC (2)\Documents\Arduino\Droid-Toolbox\Droid-Toolbox.ino: In function 'void ble_scan()':
C:\Users\Rich\Dropbox\PC (2)\Documents\Arduino\Droid-Toolbox\Droid-Toolbox.ino:1627:48: error: conversion from 'BLEScanResults*' to non-scalar type 'BLEScanResults' requested
 1627 |   BLEScanResults foundDevices = pBLEScan->start(BLE_SCAN_TIME, false);
      |                                 ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~


exit status 1

Compilation error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'String'

**Comment by ruthsarian** [comment]
The immediate solution is to downgrade your ESP32 core to a 2.x version. The newly released ESP32 3.x core is incompatible with ESP32 2.x projects. At the moment I see no method in which I can resolve this issue in a manner that supports both ESP32 2.x and 3.x cores. I will continue to research this issue.

**Comment by ruthsarian** [comment]
We've got a couple issues to contend with. ESP32 core 3.0 now uses the String object from the WString.h library to handle manufacturer's (beacon) data. ESP32 core 2.0 does not. I've found a way to support both 2.0 and 3.0. I am testing that now and will upload it shortly.

The second issue is the TFT_eSPI library also has an issue with the ESP32 3.0 core. The fix for that is either wait for a TFT_eSPI library update, or add the line `#include "driver/gpio.h"` to `TFT_eSPI_ESP32.h` and `TFT_eSPI_ESP32_S3.h`. That is something I cannot fix with my code, but I will add some if/else directives to detect ESP32 3.0 core with the old/unmodified TFT_eSPI library and error out the compilation.

**Comment by ruthsarian** [comment]
I've published update 0.72. This should resolve the compatibility issues with ESP32 core 3.0. 

Give it a test and let me know if it works for you.

**Comment by Richs1077** [comment]
fantastic thank you very much, its working great :-)

**Comment by Elcid8687** [comment]
Completed my testing.  Everything is working great.TomSent from my iPhoneOn Jun 9, 2024, at 3:18 PM, The Forgettable Mister Ruthsarian ***@***.***> wrote:﻿
Closed #7 as completed.
